home:
    path: /
    controller: App\Controller\HomeController::index

list_users:
    path: /listusers
    controller: App\Controller\UserController::listUsers

list_products:
    path: /listproducts
    controller: App\Controller\ProductController::listProducts
